cache: cargo
dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-apple-darwin
      os: osx
env: TARGET=x86_64-unknown-linux-gnu

install:
  - if [ $TRAVIS_BRANCH != master ]; then
      curl https://sh.rustup.rs -sSf |
        sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION;

      source ~/.cargo/env;

      test $TRAVIS_OS_NAME = linux || (
        curl -LSfs https://japaric.github.io/trust/install.sh |
          sh -s -- --force --git japaric/xargo --tag v0.2.1 &&
        brew tap caskroom/cask &&
        brew cask install gcc-arm-embedded
      );

      rustup component add rust-src;
    fi;


script:
  # chmod: Travis can't cache files that are not readable by "others"
  - if [ $TRAVIS_BRANCH != master ]; then
      if [ $TRAVIS_OS_NAME = linux ]; then
        sh ci/run-docker.sh $TARGET || exit 1;
      else
        sh ci/run.sh || exit 1;
      fi;

      chmod -R a+r $HOME/.cargo;
    fi

after_success:
  # NOTE(cp) mdbook won't copy files without extension into the output directory
  # We copy them manually
  - if [ $TARGET = x86_64-unknown-linux-gnu ] && [ $TRAVIS_BRANCH = master ]; then
      curl -LSfs https://japaric.github.io/trust/install.sh |
        sh -s -- --git azerupi/mdbook --tag v0.0.14 --to .;

      ./mdbook build;

      cp src/first/config book/first/;

      sh ga.sh;

      mkdir ghp-import;

      curl -Ls https://github.com/davisp/ghp-import/archive/master.tar.gz |
        tar --strip-components 1 -C ghp-import -xz;

      ./ghp-import/ghp_import.py book;

      git push -fq https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages && echo OK;
    fi

branches:
  only:
    - auto
    - try
    - master

notifications:
  email:
    on_success: never
