sudo: false

language: rust

rust: nightly

os: linux

install:
  - curl -sf "https://raw.githubusercontent.com/japaric/rust-everywhere/master/install.sh" | bash -s -- --from azerupi/mdBook --at /home/travis/.cargo/bin
  - export PATH="$PATH:/home/travis/.cargo/bin"
  - git clone --depth 1 https://github.com/davisp/ghp-import

script:
  - mdbook test
  - mdbook build

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then
      ./ghp-import/ghp_import.py -n book;
      git push -fq "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" gh-pages && echo OK;
    fi

branches:
  only: master

notifications:
  email:
    on_success: never

env:
  global:
    - secure: kJof1o+nrjiqS+w8TDDTxhApprxcjksSeovpumuc9eCMGK+4mqtjdl7AGP9AYbIYWAJEF80FJTvXyzviZs7Ov+K52YuLXVkfGSM4v1Gm9NZol6H208QLmggBhsbNzyu3v+/RUTVE3foDAANxhOVXSlLRc8thd9TfzFMRHhna63uNDNLbzE7A1a/etPGLe6QSIGXlQ/EKNUGxA2vTr15xlzm5qmLILHIEGuLEw8IMk0dd8eDYF+vQuQXFnWYL3Wx1MCqk88OK9KpMNR4Rujuewsgb3ODM56y67mRnMyu1wXoN4idXaeGy2S/M3XCdwY0vt/7WTkluTGQ3PQu8tsM5unV50/1x78xw7uEsMFd7g5IJXrsZB00vrrgXjJ/6oOZcNWhWX+LdPa+keyBau6KedPhVt9yFqhgeDIh8+qIDfVGzMmvCN8rcmWQc5z8f370kD7B9/oNp8FPazpU83gtCuWdKLKtxigVCNZWLxiMnH/y4fmNJUqOY0wbyDucNO+io72MNQTLIw5eMNWV7FDgU2pbexckUq763ZmhBhMYwo8e1583mi8jJy8j/hHYWFA4hsnA/5McdBUqxuWZLg2RgB9mJ8EYAJkGE4g2TR+W9GX6pj/xfQ7jLUe8HBgqUKBtDAMz/ZtpU1kpb4IQb1b6uoZci/zWBwCGRGtzJtzak064=
